name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: "0 7 * * MON"  # Every Monday 07:00 UTC

jobs:
  build-test-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 .

      - name: Run tests
        run: pytest -q

      - name: Generate Monthly Report
        run: python generate_report.py

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: report_output
